from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import NoReturn, TextIO

from aip.product.configured.irrbb.borrowing_inspection_evidence import (
    BorrowingInspectionEvidenceValidator,
    ValidatedBorrowingDiscoveryEvidence,
    ValidatedBorrowingHeaderEvidence,
)
from aip.product.configured.irrbb.borrowing_source_requirements import (
    BorrowingSourceEvidenceAssessor,
    BorrowingSourceSchemaAssessment,
)

BORROWING_READINESS_REPORT_TYPE = "IRRBB_BORROWING_SOURCE_READINESS"
BORROWING_READINESS_REPORT_VERSION = "2026.09.14"


class _CLIUsageError(ValueError):
    """Safe command-line usage failure without argparse process termination."""


class _SafeArgumentParser(argparse.ArgumentParser):
    """Argument parser that reports usage errors through the CLI return contract."""

    def error(self, message: str) -> NoReturn:
        raise _CLIUsageError(message)


def borrowing_readiness_report(
    assessment: BorrowingSourceSchemaAssessment,
    *,
    discovery: ValidatedBorrowingDiscoveryEvidence,
    header: ValidatedBorrowingHeaderEvidence,
) -> dict[str, object]:
    """Render metadata-only source readiness without contractual rows or balances."""

    certification = assessment.certification
    requirement_by_id = {
        requirement.requirement_id: requirement for requirement in certification.profile.requirements
    }
    return {
        "report_type": BORROWING_READINESS_REPORT_TYPE,
        "report_version": BORROWING_READINESS_REPORT_VERSION,
        "source_id": header.source_id,
        "source_reference": header.source_reference,
        "source_file_name": header.source_file_name,
        "worksheet": header.sheet_name,
        "header_row": header.header_row,
        "observed_worksheet_count": len(discovery.sheets),
        "requirement_profile": {
            "code": certification.profile.code,
            "version": certification.profile.version,
            "effective_from": certification.profile.effective_from.isoformat(),
            "source_reference": certification.profile.source_reference,
        },
        "certification_status": certification.status.value,
        "blocking_requirement_ids": list(certification.blocking_requirement_ids),
        "not_assessed_requirement_ids": list(certification.not_assessed_requirement_ids),
        "observed_labels": list(assessment.observed_labels),
        "unresolved_candidate_labels": list(assessment.unresolved_candidate_labels),
        "requirements": [
            {
                "requirement_id": item.requirement_id,
                "canonical_variable": requirement_by_id[item.requirement_id].canonical_variable,
                "status": item.status.value,
                "source_reference": item.source_reference,
                "derivation_rule_reference": item.derivation_rule_reference,
                "supplementary_source_reference": item.supplementary_source_reference,
                "evidence_reference": item.evidence_reference,
                "notes": item.notes,
            }
            for item in certification.assessments
        ],
    }


def _build_parser() -> _SafeArgumentParser:
    parser = _SafeArgumentParser(
        prog="irrbb-borrowing-readiness",
        description=(
            "Validate borrowing schema evidence and report RTILB source readiness "
            "without reading contractual data rows."
        ),
    )
    parser.add_argument(
        "--discovery-json",
        required=True,
        help="Path to borrowing-discovery.json generated by the governed inspection CLI.",
    )
    parser.add_argument(
        "--header-json",
        required=True,
        help="Path to borrowing-header.json generated by the governed inspection CLI.",
    )
    parser.add_argument(
        "--require-ready",
        action="store_true",
        help="Return exit code 3 when the validated source assessment is not READY.",
    )
    return parser


def _read_json_report(path: str) -> str:
    return Path(path).read_text(encoding="utf-8")


def _write_report(report: dict[str, object], *, stdout: TextIO) -> None:
    json.dump(report, stdout, ensure_ascii=False, indent=2, sort_keys=True)
    stdout.write("\n")


def run(
    argv: Sequence[str],
    *,
    stdout: TextIO,
    stderr: TextIO,
) -> int:
    """Validate transferred evidence and return a process-style status code."""

    try:
        args = _build_parser().parse_args(tuple(argv))
        validator = BorrowingInspectionEvidenceValidator()

        discovery = validator.parse_json_document(_read_json_report(args.discovery_json))
        if not isinstance(discovery, ValidatedBorrowingDiscoveryEvidence):
            raise ValueError("--discovery-json must contain a borrowing discovery report")

        header = validator.parse_json_document(_read_json_report(args.header_json))
        if not isinstance(header, ValidatedBorrowingHeaderEvidence):
            raise ValueError("--header-json must contain a borrowing header report")

        bundle = validator.bind(discovery, header)
        assessment = BorrowingSourceEvidenceAssessor().assess(bundle)
        _write_report(
            borrowing_readiness_report(
                assessment,
                discovery=discovery,
                header=header,
            ),
            stdout=stdout,
        )

        if args.require_ready and not assessment.certification.is_ready:
            return 3
        return 0
    except _CLIUsageError as exc:
        stderr.write(f"IRRBB borrowing readiness usage error: {exc}\n")
        return 2
    except (json.JSONDecodeError, ValueError) as exc:
        stderr.write(f"IRRBB borrowing readiness failed: {exc}\n")
        return 1
    except (FileNotFoundError, OSError):
        stderr.write("IRRBB borrowing readiness failed: evidence file access error\n")
        return 1


def main() -> int:
    """Run the metadata-only borrowing readiness diagnostic."""

    return run(sys.argv[1:], stdout=sys.stdout, stderr=sys.stderr)


if __name__ == "__main__":
    raise SystemExit(main())
