from __future__ import annotations

BORROWING_INSPECTION_REPORT_VERSION = "2026.09.10"
DISCOVERY_REPORT_TYPE = "IRRBB_BORROWING_WORKBOOK_DISCOVERY"
HEADER_REPORT_TYPE = "IRRBB_BORROWING_WORKBOOK_HEADER"
